"""Project-specific metadata for the local runtime."""

from agents.models import ProjectSpec

PROJECT_CONTEXT = {'repo_name': 'Synthesis-Octant',
 'project_name': 'Octant Signal Forge',
 'track': 'Octant Public Goods',
 'pitch': 'A signal forge that aggregates messy qualitative inputs, converts them into '
          'explainable scores, and prepares faster DPI allocation plans.',
 'idea_titles': ['Faster DPI Scoring Swarm',
                 'Qualitative Impact Evidence Engine',
                 'Private Grant Ranking Desk'],
 'architecture_summary': 'The project aggregates messy qualitative inputs, converts '
                         'them into explainable scores, and prepares public-goods '
                         'allocation plans. The contract stores round parameters and '
                         'proof commitments while Python collectors and scorers keep a '
                         'verifiable audit trail.',
 'overlap_targets': ['Venice Private Agents',
                     'Filecoin',
                     'Celo',
                     'ENS',
                     'YieldGuard',
                     'Markee'],
 'primary_contract_name': 'OctantSignalForge',
 'primary_python_module': 'octant_signal_forge',
 'category': 'public_goods',
 'daily_budget_usd': 102,
 'per_action_budget_usd': 25,
 'cooldown_seconds': 900,
 'discovery_inputs': [{'name': 'project_signals',
                       'description': 'Impact, treasury, and opportunity signals.'},
                      {'name': 'private_inputs',
                       'description': 'Sensitive ranking inputs or reviewer context.'},
                      {'name': 'execution_bundle',
                       'description': 'Micro-grant or allocation execution plan.'},
                      {'name': 'receipts',
                       'description': 'Proofs, submission notes, and final evidence.'}],
 'live_demo_steps': ['Copy .env.example to .env and fill the required keys.',
                     'Deploy the contract with forge script script/Deploy.s.sol '
                     '--broadcast for OctantSignalForge.',
                     'Run python3 scripts/run_agent.py to produce a dry run for '
                     'octant_signal_forge.',
                     'Set LIVE_MODE=true and rerun python3 scripts/run_agent.py with '
                     'real credentials.',
                     'Run python3 scripts/render_submission.py and attach TxIDs plus '
                     'repo links.'],
 'partners': [{'name': 'Octant',
               'docs_url': 'https://octant.app/',
               'env_vars': ['OCTANT_SIGNAL_URL'],
               'endpoint_env': 'OCTANT_SIGNAL_URL',
               'action_kind': 'rest_json',
               'purpose': 'Publish scored public-goods signals and DPI artifacts.'},
              {'name': 'Venice',
               'docs_url': 'https://docs.venice.ai/',
               'env_vars': ['VENICE_API_KEY',
                            'VENICE_CHAT_COMPLETIONS_URL',
                            'VENICE_MODEL'],
               'endpoint_env': 'VENICE_CHAT_COMPLETIONS_URL',
               'action_kind': 'rest_json',
               'purpose': 'Run private reasoning over sensitive inputs.'},
              {'name': 'Filecoin',
               'docs_url': 'https://docs.filecoin.cloud/',
               'env_vars': ['FILECOIN_API_TOKEN', 'FILECOIN_UPLOAD_URL'],
               'endpoint_env': 'FILECOIN_UPLOAD_URL',
               'action_kind': 'file_upload',
               'purpose': 'Persist proofs, logs, and evidence bundles offchain.'},
              {'name': 'Celo',
               'docs_url': 'https://docs.celo.org/',
               'env_vars': ['CELO_RPC_URL'],
               'endpoint_env': '',
               'action_kind': 'contract_call',
               'purpose': 'Settle stablecoin-native transfers on Celo rails.'},
              {'name': 'ENS',
               'docs_url': 'https://docs.ens.domains/',
               'env_vars': ['ENS_NAME'],
               'endpoint_env': '',
               'action_kind': 'contract_call',
               'purpose': 'Publish human-readable coordination and identity receipts.'},
              {'name': 'Markee',
               'docs_url': 'https://markee.xyz/',
               'env_vars': ['MARKEE_API_KEY', 'MARKEE_MESSAGE_URL'],
               'endpoint_env': 'MARKEE_MESSAGE_URL',
               'action_kind': 'rest_json',
               'purpose': 'Publish GitHub-adjacent build stories and repo messages.'}],
 'actions': [{'id': 'octant_signal_publish',
              'target': 'octant',
              'purpose': 'Use Octant for a bounded action in this repo.',
              'partner': 'Octant',
              'action_kind': 'rest_json',
              'max_amount_usd': 25,
              'priority': 100,
              'sensitivity': 'medium',
              'notes': ['Call Octant only after a dry-run artifact exists.',
                        'Use https://octant.app/ for credential setup.']},
             {'id': 'venice_private_analysis',
              'target': 'venice',
              'purpose': 'Use Venice for a bounded action in this repo.',
              'partner': 'Venice',
              'action_kind': 'rest_json',
              'max_amount_usd': 5,
              'priority': 95,
              'sensitivity': 'high',
              'notes': ['Call Venice only after a dry-run artifact exists.',
                        'Use https://docs.venice.ai/ for credential setup.']},
             {'id': 'filecoin_proof_store',
              'target': 'filecoin',
              'purpose': 'Use Filecoin for a bounded action in this repo.',
              'partner': 'Filecoin',
              'action_kind': 'file_upload',
              'max_amount_usd': 20,
              'priority': 90,
              'sensitivity': 'medium',
              'notes': ['Call Filecoin only after a dry-run artifact exists.',
                        'Use https://docs.filecoin.cloud/ for credential setup.']},
             {'id': 'celo_payment_settle',
              'target': 'celo',
              'purpose': 'Use Celo for a bounded action in this repo.',
              'partner': 'Celo',
              'action_kind': 'contract_call',
              'max_amount_usd': 150,
              'priority': 85,
              'sensitivity': 'low',
              'notes': ['Call Celo only after a dry-run artifact exists.',
                        'Use https://docs.celo.org/ for credential setup.']},
             {'id': 'ens_ens_publish',
              'target': 'ens',
              'purpose': 'Use ENS for a bounded action in this repo.',
              'partner': 'ENS',
              'action_kind': 'contract_call',
              'max_amount_usd': 5,
              'priority': 80,
              'sensitivity': 'low',
              'notes': ['Call ENS only after a dry-run artifact exists.',
                        'Use https://docs.ens.domains/ for credential setup.']},
             {'id': 'markee_repo_message',
              'target': 'markee',
              'purpose': 'Use Markee for a bounded action in this repo.',
              'partner': 'Markee',
              'action_kind': 'rest_json',
              'max_amount_usd': 5,
              'priority': 75,
              'sensitivity': 'low',
              'notes': ['Call Markee only after a dry-run artifact exists.',
                        'Use https://markee.xyz/ for credential setup.']}]}


def build_project_spec() -> ProjectSpec:
    """Return the repository-specific project metadata."""
    return ProjectSpec.from_dict(PROJECT_CONTEXT)
